---
title: "simulated data"
author: "Aleix Alcacer"
date: "1/11/2022"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(reshape2)
library(ggplot2)
```

## Amplitude

```{r}
set.seed(1234)

out_rate <- .05
p <- 25
n <- 100
cl <- 0.25 #proportion of samples of each cluster (between 0 and 1)
t <- seq(0, 1, len = p)
d <- as.matrix(dist(t, upper = T, diag = T))

# Generate model
t.cov <- 0.3 * exp(-1 / 0.3 * d)  # covariance function in time
L <- chol(t.cov)  # Cholesky decomposition
mu <- 10 * t * (1 - t) ^ (3 / 2)

cluster = "multiple"

### Generate Data
if (cluster == "single") {
    e = matrix(rnorm(n * p), p, n)
    y = mu + t(L) %*% e
} else {
    # Generate model
    e = matrix(rnorm(n * p * cl), p, n * cl)
    y1 = mu + t(L) %*% e
    
    e = matrix(rnorm(n * p * (1 - cl)), p, n * (1 - cl))
    y2 = 10 * mu + t(L) %*% e
    
    y = cbind(y1, y2)
}

### Generate Outliers
out <- sort(sample(1:n, n * out_rate))
for (i in out) {
    e = rnorm(p)
    y[, i] = 5 * mu + t(L) %*% e
}

data = t(y)

y_labels = rep(0, n)
y_labels[out] = 1

p_data <- as_tibble(data) %>% add_column(class = y_labels, .before = T) %>% rownames_to_column(var = "id")
p_values <- as.matrix(p_data[c(-1, -2)])

m_data <- p_data %>% melt(id.vars = c("id", "class"))

g <- ggplot(m_data, aes(x=variable, y=value, group=id)) +
    geom_line(aes(color=factor(class),  alpha=class)) +
    labs(color='Class') +
    theme_void() +
        scale_colour_manual(values=c("darkviolet", "deeppink"), labels=c("No Outlier", "Outlier")) +
    scale_alpha(guide = 'none')
    

ggsave(file="results/examples/amplitude-example.svg", plot=g, width=5, height=4)
ggsave(file="results/examples/amplitude-example.png", plot=g, width=5, height=4)
```

## Shift

```{r}
set.seed(1234)

out_rate <- .05
p <- 25
n <- 100
cl <- 0.25 #proportion of samples of each cluster (between 0 and 1)
t <- seq(0, 1, len = p)
d <- as.matrix(dist(t, upper = T, diag = T))

# Generate model
t.cov <- 0.3 * exp(-1 / 0.3 * d)  # covariance function in time
L <- chol(t.cov)  # Cholesky decomposition
mu <- 30 * t * (1 - t) ^ (3 / 2)

cluster = "multiple"

### Generate Data
if (cluster == "single") {
    e = matrix(rnorm(n * p), p, n)
    y = mu + t(L) %*% e
} else {
    # Generate model
    e = matrix(rnorm(n * p * cl), p, n * cl)
    y1 = mu + t(L) %*% e
    
    e = matrix(rnorm(n * p * (1 - cl)), p, n * (1 - cl))
    y2 = 6 + mu + t(L) %*% e
    
    y = cbind(y1, y2)
}

### Generate Outliers
out <- sort(sample(1:n, n * out_rate))
for (i in out) {
    e = rnorm(p)
    y[, i] = 3 + mu + t(L) %*% e
}

data = t(y)

y_labels = rep(0, n)
y_labels[out] = 1

p_data <- as_tibble(data) %>% add_column(class = y_labels, .before = T) %>% rownames_to_column(var = "id")
p_values <- as.matrix(p_data[c(-1, -2)])

m_data <- p_data %>% melt(id.vars = c("id", "class"))

g <- ggplot(m_data, aes(x=variable, y=value, group=id)) +
    geom_line(aes(color=factor(class), alpha=class)) +
    labs(color='Class') +
    theme_void() +
        scale_colour_manual(values=c("darkviolet", "deeppink"), labels=c("No Outlier", "Outlier")) +
    scale_alpha(guide = 'none')

ggsave(file="results/examples/shift-example.svg", plot=g, width=5, height=4)
ggsave(file="results/examples/shift-example.png", plot=g, width=5, height=4)
```

## Shift (horizontal)

```{r}
set.seed(1234)

out_rate <- .05
p <- 25
n <- 100
cl <- 0.25 #proportion of samples of each cluster (between 0 and 1)
t <- seq(0, 1, len = p)
d <- as.matrix(dist(t, upper = T, diag = T))

# Generate model
t.cov <- 0.3 * exp(-1 / 0.3 * d)  # covariance function in time
L <- chol(t.cov)  # Cholesky decomposition
mu <- 30 * t * (1 - t) ^ 2

cluster = "multiple"

### Generate Data
if (cluster == "single") {
    e = matrix(rnorm(n * p), p, n)
    y = mu + t(L) %*% e
} else {
    # Generate model
    e = matrix(rnorm(n * p * cl), p, n * cl)
    y1 = mu + t(L) %*% e
    
    e = matrix(rnorm(n * p * (1 - cl)), p, n * (1 - cl))
    t2 <- t + 0.3
    mu2 <- 30 * t2 * (1 - t2) ^ 2
    
    y2 = mu2 + t(L) %*% e
    
    y = cbind(y1, y2)
}

### Generate Outliers
out <- sort(sample(1:n, n * out_rate))
for (i in out) {
    e = rnorm(p)
    t3 <- t + 0.15
    mu3 <- 30 * t3 * (1 - t3) ^ 2
    y[, i] = mu3 + t(L) %*% e
}

data = t(y)

y_labels = rep(0, n)
y_labels[out] = 1

p_data <- as_tibble(data) %>% add_column(class = y_labels, .before = T) %>% rownames_to_column(var = "id")
p_values <- as.matrix(p_data[c(-1, -2)])

m_data <- p_data %>% melt(id.vars = c("id", "class"))

g <- ggplot(m_data, aes(x=variable, y=value, group=id)) +
    geom_line(aes(color=factor(class), alpha=class)) +
    labs(color='Class') +
    theme_void() +
        scale_colour_manual(values=c("darkviolet", "deeppink"), labels=c("No Outlier", "Outlier")) +
    scale_alpha(guide = 'none')

ggsave(file="results/examples/shift-h-example.svg", plot=g, width=5, height=4)
ggsave(file="results/examples/shift-h-example.png", plot=g, width=5, height=4)
```


## Isolated

```{r}
set.seed(1234)

out_rate <- .05
p <- 25
n <- 100
cl <- 0.25 #proportion of samples of each cluster (between 0 and 1)
t <- seq(0, 1, len = p)
d <- as.matrix(dist(t, upper = T, diag = T))

# Generate model
t.cov <- 0.3 * exp(-1 / 0.3 * d)  # covariance function in time
L <- chol(t.cov)  # Cholesky decomposition
mu <- 30 * t * (1 - t) ^ (3 / 2)

cluster = "multiple"

### Generate Data
e = matrix(rnorm(n * p), p, n)
y = mu + t(L) %*% e

iso_interval = seq(-2, 2, .5)

if (cluster == "multiple") {
    ind = sample(1:(n/2), n * cl)
    for (i in ind) {
        y[, i] = y[, i] + 15 * c(rep(0, p - length(iso_interval)), dnorm(iso_interval))
    }
}

### Generate Outliers
out<-sample((n/2):n, n * out_rate)
for (i in out){
    y[,i] =  y[, i] + 10 * c(dnorm(iso_interval), rep(0, p - length(iso_interval)))
}
        
data = t(y)

y_labels = rep(0, n)
y_labels[out] = 1

p_data <- as_tibble(data) %>% add_column(class = y_labels, .before = T) %>% rownames_to_column(var = "id")
p_values <- as.matrix(p_data[c(-1, -2)])

m_data <- p_data %>% melt(id.vars = c("id", "class"))

g <- ggplot(m_data, aes(x=variable, y=value, group=id)) +
    geom_line(aes(color=factor(class),  alpha=class)) +
    labs(color='Class') +
    theme_void() +
    scale_colour_manual(values=c("darkviolet", "deeppink"), labels=c("No Outlier", "Outlier")) +
    scale_alpha(guide = 'none')

ggsave(file="results/examples/isolated-example.svg", plot=g, width=5, height=4)
ggsave(file="results/examples/isolated-example.png", plot=g, width=5, height=4)
```


## Shape

```{r}
set.seed(1234)

out_rate <- .05
p <- 25
n <- 100
cl <- 0.25 #proportion of samples of each cluster (between 0 and 1)
t <- seq(0, 1, len = p)
d <- as.matrix(dist(t, upper = T, diag = T))

# Generate model
t.cov <- 0.3 * exp(-1 / 0.3 * d)  # covariance function in time
L <- chol(t.cov)  # Cholesky decomposition
mu <- 30 * t * (1 - t) ^ (3 / 2)

cluster = "multiple"

### Generate Data
e = matrix(rnorm(n * p), p, n)
y = mu + t(L) %*% e

iso_interval = seq(-2, 2, .5)

if (cluster == "multiple") {
    n_2 <- ceiling(n * cl)
    mu_2 <- 10 * t^(1/3) * (1 - t)^(3)
    e_2 = matrix(rnorm(n_2 * p), p, n_2) / 2
    y_2 = mu_2 + t(L) %*% e_2
    y[, 1:n_2] = y_2
}

### Generate Outliers
out<-sample((n/2):n, n * out_rate)
for (i in out){
    mu = 15 * t^2 * (1-t)^2
    y[,i] =  mu + t(L) %*% (rnorm(p) / 2)
}

data = t(y)

y_labels = rep(0, n)
y_labels[out] = 1

p_data <- as_tibble(data) %>% add_column(class = y_labels, .before = T) %>% rownames_to_column(var = "id")
p_values <- as.matrix(p_data[c(-1, -2)])

m_data <- p_data %>% melt(id.vars = c("id", "class"))

g <- ggplot(m_data, aes(x=variable, y=value, group=id)) +
    geom_line(aes(color=factor(class), alpha=class)) +
    labs(color='Class') +
    theme_void() +
    scale_colour_manual(values=c("darkviolet", "deeppink"), labels=c("No Outlier", "Outlier")) +
    scale_alpha(guide = 'none')

ggsave(file="results/examples/shape-example.svg", plot=g, width=5, height=4)
ggsave(file="results/examples/shape-example.png", plot=g, width=5, height=4)
```